import type { Cat } from "@/app/_types/cat";

export const MOCK_CATS: Cat[] = [
	{
		id: "1",
		name: "치즈",
		breed: "코리안 숏헤어",
		personality: "활발한",
		discoveredAt: "한강공원 벤치",
		discoveredDate: "2024.01.15",
		rarity: "common",
		description: "햇살을 좋아하는 밝은 성격의 고양이예요. 사람들과 놀기를 좋아해요.",
		favoriteFood: "참치",
		hobby: "낮잠자기",
		isDiscovered: true,
	},
	{
		id: "2",
		name: "루나",
		breed: "러시안 블루",
		personality: "신비로운",
		discoveredAt: "북촌 한옥마을",
		discoveredDate: "2024.01.12",
		rarity: "rare",
		description: "달빛처럼 아름다운 회색 털을 가진 우아한 고양이예요.",
		favoriteFood: "연어",
		hobby: "달구경",
		isDiscovered: true,
	},
	{
		id: "3",
		name: "모카",
		breed: "페르시안",
		personality: "우아한",
		discoveredAt: "홍대 카페거리",
		discoveredDate: "2024.01.10",
		rarity: "epic",
		description: "커피색 털이 매력적인 고급스러운 고양이예요. 조용한 곳을 좋아해요.",
		favoriteFood: "크림",
		hobby: "독서",
		isDiscovered: true,
	},
	{
		id: "4",
		name: "코코",
		breed: "브리티시 숏헤어",
		personality: "온순한",
		discoveredAt: "경복궁 돌담길",
		discoveredDate: "2024.01.08",
		rarity: "common",
		description: "둥글둥글한 얼굴이 매력적인 온화한 성격의 고양이예요.",
		favoriteFood: "닭가슴살",
		hobby: "햇볕쬐기",
		isDiscovered: true,
	},
	{
		id: "5",
		name: "별이",
		breed: "스코티시 폴드",
		personality: "장난꾸러기",
		discoveredAt: "63빌딩",
		discoveredDate: "2024.01.05",
		rarity: "rare",
		description: "별처럼 반짝이는 눈을 가진 귀여운 고양이예요. 높은 곳을 좋아해요.",
		favoriteFood: "츄르",
		hobby: "별보기",
		isDiscovered: true,
	},
	{
		id: "6",
		name: "망고",
		breed: "아메리칸 숏헤어",
		personality: "친근한",
		discoveredAt: "이태원 골목길",
		discoveredDate: "2024.01.03",
		rarity: "common",
		description: "노란 털색이 망고 같아서 망고라는 이름을 얻었어요. 사람을 좋아해요.",
		favoriteFood: "멸치",
		hobby: "사람 따라다니기",
		isDiscovered: true,
	},
	{
		id: "7",
		name: "미르",
		breed: "메인쿤",
		personality: "당당한",
		discoveredAt: "청계천 산책로",
		discoveredDate: "2024.01.01",
		rarity: "epic",
		description: "큰 체구와 위엄 있는 모습이 인상적인 고양이예요. 리더십이 강해요.",
		favoriteFood: "소고기",
		hobby: "영역 순찰",
		isDiscovered: true,
	},
	{
		id: "8",
		name: "구름",
		breed: "터키시 앙고라",
		personality: "몽환적인",
		discoveredAt: "서울숲 연못가",
		discoveredDate: "2023.12.28",
		rarity: "rare",
		description: "구름처럼 하얀 털이 아름다운 고양이예요. 물가를 좋아해요.",
		favoriteFood: "우유",
		hobby: "물놀이 구경",
		isDiscovered: true,
	},
	{
		id: "9",
		name: "솜이",
		breed: "랙돌",
		personality: "온화한",
		discoveredAt: "강남 도서관 앞",
		discoveredDate: "2023.12.25",
		rarity: "rare",
		description: "인형처럼 부드러운 털과 온순한 성격을 가진 고양이예요. 안아주는 것을 좋아해요.",
		favoriteFood: "닭고기",
		hobby: "안겨있기",
		isDiscovered: true,
	},
	{
		id: "10",
		name: "턱시",
		breed: "턱시도",
		personality: "신사적인",
		discoveredAt: "명동 성당 계단",
		discoveredDate: "2023.12.22",
		rarity: "epic",
		description: "턱시도를 입은 것처럼 흑백 털이 멋진 신사 고양이예요. 품격 있는 모습이 인상적이에요.",
		favoriteFood: "고급 사료",
		hobby: "클래식 음악 감상",
		isDiscovered: true,
	},
	{
		id: "11",
		name: "샤미",
		breed: "샴",
		personality: "수다쟁이",
		discoveredAt: "인사동 전통찻집",
		discoveredDate: "2023.12.20",
		rarity: "rare",
		description: "아름다운 파란 눈과 포인트 컬러가 매력적인 고양이예요. 말이 많고 사교적이에요.",
		favoriteFood: "생선회",
		hobby: "수다떨기",
		isDiscovered: true,
	},
	{
		id: "12",
		name: "황금이",
		breed: "골든 리트리버 믹스",
		personality: "고귀한",
		discoveredAt: "경복궁 근정전",
		discoveredDate: "",
		rarity: "legendary",
		description: "황금빛 털을 가진 전설적인 고양이예요. 왕실의 기품이 느껴져요.",
		favoriteFood: "황금 참치",
		hobby: "왕좌에 앉기",
		isDiscovered: false,
	},
	{
		id: "13",
		name: "은하",
		breed: "시베리안",
		personality: "신비로운",
		discoveredAt: "남산타워 전망대",
		discoveredDate: "",
		rarity: "legendary",
		description: "은하수처럼 아름다운 털무늬를 가진 신비한 고양이예요.",
		favoriteFood: "별사탕",
		hobby: "별자리 관찰",
		isDiscovered: false,
	},
	{
		id: "14",
		name: "다이아",
		breed: "벵갈",
		personality: "화려한",
		discoveredAt: "청담동 갤러리",
		discoveredDate: "",
		rarity: "legendary",
		description: "다이아몬드처럼 반짝이는 무늬가 특별한 고양이예요.",
		favoriteFood: "캐비어",
		hobby: "보석 구경",
		isDiscovered: false,
	},
	{
		id: "15",
		name: "바닐라",
		breed: "노르웨이 숲",
		personality: "차분한",
		discoveredAt: "덕수궁 돌담길",
		discoveredDate: "2023.12.18",
		rarity: "common",
		description: "크림색 털이 바닐라 같은 온순한 고양이예요. 조용한 곳을 좋아해요.",
		favoriteFood: "홍차",
		hobby: "나무 그늘에서 쉬기",
		isDiscovered: true,
	},
	{
		id: "16",
		name: "콩이",
		breed: "먼치킨",
		personality: "귀여운",
		discoveredAt: "홍대 놀이터",
		discoveredDate: "2023.12.15",
		rarity: "common",
		description: "짧은 다리가 매력적인 작고 귀여운 고양이예요. 활발하게 뛰어다녀요.",
		favoriteFood: "도넛",
		hobby: "공 굴리기",
		isDiscovered: true,
	},
	{
		id: "17",
		name: "토리",
		breed: "아비시니안",
		personality: "활동적인",
		discoveredAt: "올림픽공원 잔디밭",
		discoveredDate: "",
		rarity: "common",
		description: "갈색 털이 아름다운 활발한 고양이예요. 뛰어다니기를 좋아해요.",
		favoriteFood: "벌꿀",
		hobby: "달리기",
		isDiscovered: false,
	},
	{
		id: "18",
		name: "보리",
		breed: "코리안 숏헤어",
		personality: "순수한",
		discoveredAt: "잠실나루",
		discoveredDate: "",
		rarity: "common",
		description: "보리색 털을 가진 순박한 고양이예요. 자연을 좋아해요.",
		favoriteFood: "보리차",
		hobby: "풀밭 굴러다니기",
		isDiscovered: false,
	},
	{
		id: "19",
		name: "복이",
		breed: "코리안 숏헤어",
		personality: "복스러운",
		discoveredAt: "종묘 앞",
		discoveredDate: "",
		rarity: "common",
		description: "복을 가져다준다는 전설이 있는 고양이예요. 둥글둥글한 체형이 귀여워요.",
		favoriteFood: "복어",
		hobby: "복주머니 만지기",
		isDiscovered: false,
	},
	{
		id: "20",
		name: "오팔",
		breed: "오리엔탈 숏헤어",
		personality: "신비로운",
		discoveredAt: "동대문 보물상가",
		discoveredDate: "",
		rarity: "rare",
		description: "오팔처럼 색이 변하는 신비한 털을 가진 고양이예요.",
		favoriteFood: "무지개 젤리",
		hobby: "보석 수집",
		isDiscovered: false,
	},
	{
		id: "21",
		name: "루비",
		breed: "소말리",
		personality: "열정적인",
		discoveredAt: "홍대역",
		discoveredDate: "",
		rarity: "epic",
		description: "루비처럼 붉은 털이 아름다운 열정적인 고양이예요. 음악을 좋아해요.",
		favoriteFood: "체리",
		hobby: "댄스",
		isDiscovered: false,
	},
	{
		id: "22",
		name: "프리즘",
		breed: "스핑크스",
		personality: "초월적인",
		discoveredAt: "롯데타워 전망대",
		discoveredDate: "",
		rarity: "special",
		description: "빛을 굴절시키는 신비한 능력을 가진 전설의 고양이예요. 세상에 단 한 마리뿐이에요.",
		favoriteFood: "이슬",
		hobby: "빛 굴절시키기",
		isDiscovered: false,
	},
];

export const RARITY_COLORS = {
	common: "bg-gray-100 text-gray-700 border-gray-300",
	rare: "bg-blue-100 text-blue-700 border-blue-300",
	epic: "bg-purple-100 text-purple-700 border-purple-300",
	legendary: "bg-yellow-100 text-yellow-700 border-yellow-300",
	special: "bg-gradient-to-r from-pink-100 to-rose-100 text-pink-700 border-pink-300",
};

export const RARITY_LABELS = {
	common: "일반",
	rare: "레어",
	epic: "에픽",
	legendary: "레전드",
	special: "스페셜",
};

export const GRADE_ORDER = {
	special: 0,
	legendary: 1,
	epic: 2,
	rare: 3,
	common: 4,
};
