import type { Cat } from "@/app/_types/cat";

export const MOCK_CATS: Cat[] = [
	{
		id: "cat-001",
		name: "루나",
		breed: "코리안 숏헤어",
		personality: "호기심 많은",
		discoveredAt: "강남구 선릉역",
		discoveredDate: "2024-01-15",
		rarity: "common",
		description: "파란 목걸이를 한 회색 고양이. 사람을 잘 따름.",
		favoriteFood: "참치캔",
		hobby: "높은 곳 올라가기",
		isDiscovered: true,
	},
	{
		id: "cat-002",
		name: "미도리",
		breed: "러시안 블루",
		personality: "신중한",
		discoveredAt: "마포구 망원한강공원",
		discoveredDate: "2024-01-20",
		rarity: "rare",
		description: "은회색 털을 가진 우아한 고양이. 조용한 성격.",
		favoriteFood: "연어",
		hobby: "일광욕",
		isDiscovered: true,
	},
	{
		id: "cat-003",
		name: "타로",
		breed: "페르시안",
		personality: "우아한",
		discoveredAt: "종로구 북촌한옥마을",
		discoveredDate: "2024-02-01",
		rarity: "epic",
		description: "긴 털을 가진 고급스러운 고양이. 전통 한옥과 잘 어울림.",
		favoriteFood: "고급사료",
		hobby: "그루밍",
		isDiscovered: false,
	},
	{
		id: "cat-004",
		name: "골드",
		breed: "메인쿤",
		personality: "활발한",
		discoveredAt: "용산구 한강공원",
		discoveredDate: "2024-02-14",
		rarity: "legendary",
		description: "황금빛 털을 가진 대형 고양이. 매우 희귀함.",
		favoriteFood: "프리미엄 간식",
		hobby: "사냥놀이",
		isDiscovered: false,
	},
	{
		id: "cat-005",
		name: "스페셜",
		breed: "뱅갈",
		personality: "신비로운",
		discoveredAt: "강남구 봉은사",
		discoveredDate: "2024-03-01",
		rarity: "special",
		description: "표범 무늬를 가진 신비로운 고양이. 전설급 희귀성.",
		favoriteFood: "특별 요리",
		hobby: "명상",
		isDiscovered: false,
	},
];
